"""'fourth_3'

Revision ID: 979196f7b6c3
Revises: a00939e8bbee
Create Date: 2025-10-27 13:30:43.578775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '979196f7b6c3'
down_revision: Union[str, None] = 'a00939e8bbee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_post_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_post_id')
    # ### end Alembic commands ###
