"""'fourth_4'

Revision ID: 9f731d2624f7
Revises: 979196f7b6c3
Create Date: 2025-10-27 13:57:13.607052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f731d2624f7'
down_revision: Union[str, None] = '979196f7b6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'is_sent')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('is_sent', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
